### ISSUE TITLE
heatedWaterChannel Test

### ISSUE THREAD

**Issue by jrood-nrel** [NaluCFD/NaluRtest#22]
Stefan,

What are your thoughts on me splitting the `heatedWaterChannel` test into two tests? It seems to me like it could essentially be a `heatedWaterChannelEdge` test with a restart, and a `heatedWaterChannelElem` test. Though I may be missing something if there is a nuance in this one. I think this is my last test to reorganize.

**Comment by spdomin** [comment]
Generally, the only complexity in such combined tests rests in the ability to adequately test restart. Since the code allows for edge- and element-based schemes to be mixed and matched, we need this capability in the test suite. I think that the heliumPlume tests this code path.

This specific test runs three cases: two with edge and one with element - with a restart mixed on the edge-based scheme **only**.

I do not understand the rules enough to define a path forward. However, in general, we need the flexibility to allow for restart tests between edge- and element-based.

In this specific case, it was probably an omission that I did not write the element-based input file to use the edge-based restart results.

**Comment by jrood-nrel** [comment]
Ok, I have tests that restart in CTest, so this shouldn't be a problem.

As I stated in the pull request, I think it would be simple in the future to just impose a short readme with each test that describes it, and we can have a strict convention that the name of the test implies the name of the files it uses on the command line.
